apiVersion: v1
kind: Service
metadata:
  name: yolo-client
spec:
  selector:
    app: yolo-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposes the service externally with a cloud provider's load balancer