apiVersion: v1
kind: Service
metadata:
  name: yolo-backend
spec:
  selector:
    app: yolo-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP  # Only exposes the service within the cluster